### ISSUE TITLE
Using something like react or vue.js for frontend

### ISSUE THREAD

**Issue by tonymadbrain** [tonymadbrain/flickr_wrap#3]

**Comment by kirillku** [comment]
Привет, можешь подробнее описать?
Хочешь просто перенести текущий фронтенд на реакт не меняя функциональности?

**Comment by tonymadbrain** [comment]
Привет, да не меняя функциональности, если нужны правки по API пиши

**Comment by kirillku** [comment]
Я установил руби и попробовал запустить проект чтобы посмотреть как все работает, но получаю ошибку, что неверный ключ.

```bash
$ bundle exec rackup config.ru -p 3000
C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/flickraw-0.9.8/lib/flickraw/api.rb:132:in `process_response': 'flickr.reflection.getMethods' - Invalid API Key (Key has inv
alid format) (FlickRaw::FailedResponse)
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/flickraw-0.9.8/lib/flickraw/api.rb:59:in `call'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/flickraw-0.9.8/lib/flickraw/api.rb:48:in `initialize'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/flickraw-0.9.8/lib/flickraw.rb:20:in `new'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/flickraw-0.9.8/lib/flickraw.rb:20:in `flickr'
        from C:/Users/kubry/dev/flickr_wrap/app.rb:49:in `<top (required)>'
        from C:/Users/kubry/dev/flickr_wrap/config.ru:1:in `require'
        from C:/Users/kubry/dev/flickr_wrap/config.ru:1:in `block in <main>'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
        from C:/Users/kubry/dev/flickr_wrap/config.ru:in `new'
        from C:/Users/kubry/dev/flickr_wrap/config.ru:in `<main>'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:272:in `start'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:147:in `start'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.4/bin/rackup:4:in `<top (required)>'
        from C:/RailsInstaller/Ruby2.2.0/bin/rackup:23:in `load'
        from C:/RailsInstaller/Ruby2.2.0/bin/rackup:23:in `<main>'
```

Создал файл со всеми переменными точно так же, как было написано в `readme`. Либо мне надо свои ключи получать?

**Comment by tonymadbrain** [comment]
> Либо мне надо свои ключи получать?

Нужно свои ключи получить, в readme рыба для примера написана. Вот здесь - https://www.flickr.com/services/api/ можно найти информацию по ключам
